language: shell

sudo: false

git:
  - submodules: false

install:
  - wget -qO- https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz | tar -xJv
  - cp shellcheck-latest/shellcheck .
  - ./shellcheck --version

jobs:
  include:
    - stage: shellcheck
      script: ./shellcheck .profile
    - script: ./shellcheck .kshrc
    - script: ./shellcheck .aliases
    - script: ./shellcheck .xinitrc
    - script: ./shellcheck .xsession
    - stage: vimlint
      script: ./.build/lib/vim-vimlint/bin/vimlint.sh -l ./.build/lib/vim-vimlint -p ./.build/lib/vim-vimlparser -v .vimrc

stages:
  - shellcheck
  - vimlint
