language: shell
script:
  - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'
  - bash -c 'shopt -s globstar nullglob; shellcheck .profile'
  - bash -c 'shopt -s globstar nullglob; shellcheck .aliases'
