language: shell

git:
  - submodules: false

jobs:
  include:
    - stage: shellcheck
      script: shellcheck .profile
    - script: shellcheck .kshrc
    - script: shellcheck .aliases
    - script: shellcheck .xinitrc
    - script: shellcheck .xsession
    - stage: vimlint
      before_script:
        - git clone https://github.com/syngan/vim-vimlint    /tmp/vim-vimlint
        - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
      script: /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc

stages:
  - shellcheck
  - vimlint
