git:
  - submodules: false

before_script:
  - git clone https://github.com/syngan/vim-vimlint    /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

jobs:
  include:
    language: shell
    script: shellcheck .profile
    script: shellcheck .aliases
    script: /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v autoload
