language: shell

git:
  - submodules: false

jobs:
  include:
    before_script:
      - git clone https://github.com/syngan/vim-vimlint    /tmp/vim-vimlint
      - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    script: shellcheck .profile
    script: shellcheck .kshrc
    script: shellcheck .aliases
    script: /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc
