---

# This file defines backmerge actions
name: Backmerge

# Automate on pull request close events
on:
  pull_request:
    branches:
      - master
    types:
      - closed

# Define a job for each automatic task
jobs:

  # This job merges main into all feature branches
  main_onto_feature_branches:

    # Only run this action if the PRwas closed by merging into main
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:

      # Create new branch and push to remote
      - uses: actions/checkout@v2
        with:
          ref: main

      # Set environment variables to allow configuration
      - name: Set env
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          git config --local user.email "76186754+yuri-norwood@users.noreply.github.com"
          git config --local user.name  "Yuri Norwood"

      # Loop over all branches and backmerge
      - name: Backmerge All
        run: |
          for BRANCH in $(git branch -r | sed 's/^\s*origin\///g')
          do
            echo "Backmerging ${BRANCH}"
            git fetch --unshallow
            git checkout "${BRANCH}"
            git pull
            git merge --no-ff main -m "Backmerge"
            git push
          done
