name: editorconfig

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
