---

# This file defines issue automation actions
name: issue automation

# Automate on issue create events
on:
  issues:
    types: [opened]

# Define a job for each automatic task
jobs:

  # This job creates new branches for new issues
  labeler:
    runs-on: ubuntu-latest
    steps:

      # Set environment vairables to allow configuration
      - uses: actions/checkout@master
      - name: Set env
        run: |
          echo "GITHUB_NEW_BRANCH=$(echo ${{ github.event.issue.number }}-${{ github.event.issue.title }} | tr '[:space:]' '_')" >> $GITHUB_ENV
          echo "GITHUB_REPO_URL=https://${{ secrets.GITHUB_TOKEN }}@github.com/yuri-norwood/dotfiles.git" >> $GITHUB_ENV

      # Create new branch and push to remote
      - uses: actions/checkout@v1
      - name: Auto branch
        run: |
          git checkout -b "${{ env.GITHUB_NEW_BRANCH }}"
          git push --set-upstream "${{ env.GITHUB_NEW_BRANCH }}" "${{ env.GITHUB_REPO_URL }}"
