---

# This file defines linting actions
name: Lint

# Lint on all pull request events and when merging to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define a job for each automatic task
jobs:

  # Lint markdown files
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Lint all markdown files
      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: '.**/*.md'

  # Lint yaml files
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Lint all .yml files
      - name: yaml lint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: parsable
          config_data: |
            extends: default
            ignore:
              test/**/*.yml
            rules:
              line-length: disable
              truthy:
                check-keys: false
                allowed-values:
                  - "true"
                  - "false"

  # Enforce editroconfig compliance
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Check all files against the .editorconfig
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0

  # Lint shellscript files
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Lint shell scripts
      - name: shellcheck profile
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .profile

      # Lint user aliases
      - name: shellcheck aliases
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .config/aliases/*

      # Lint pfetch config - NOTE: Ignore SC2034 as it is imported
      - name: shellcheck pfetch config
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .config/pfetch/config
        env:
          SHELLCHECK_OPTS: -e SC2034

  # Lint vimscript files
  vimscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Lint vimrc
      - name: Vint vimrc
        uses: ludvighz/vint-action@v1
        with:
          path: .config/vim/vimrc

      # Lint exrc
      - name: Vint .exrc
        uses: ludvighz/vint-action@v1
        with:
          path: .config/vim/exrc
