name: Makefile based tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make clean test_shellcheck
  vimlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make clean test_vimlint
