name: makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make clean test_shellcheck
  make_vimlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make clean test_vimlint
