name: make_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vimlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make clean test_vimlint
        run: cd .build && make clean test_vimlint
