---

name: metrics

on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # Dotfile specific metrics
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Pacific/Auckland
          filename: .github/metrics.svg
          base: header
          query: '{"repo":"dotfiles"}'

          # Show followup to issues and pulls
          plugin_followup: true

          # Show license details
          plugin_licenses: true
          plugin_licenses_ratio: true
          plugin_licenses_legal: true
