name: reviewdog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: shellcheck .profile
      - uses: actions/checkout@v1
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: .
          pattern: .profile
          shellcheck_flags: -e SC1090,SC2155
      - name: shellcheck .kshrc
      - uses: actions/checkout@v1
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: .
          pattern: .kshrc
