name: shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck .profile
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .profile
      - uses: actions/checkout@v1
      - name: shellcheck .kshrc
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .kshrc
      - uses: actions/checkout@v1
      - name: shellcheck .aliases
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .aliases
      - uses: actions/checkout@v1
      - name: shellcheck .xinitrc
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .xinitrc
      - uses: actions/checkout@v1
      - name: shellcheck .xsession
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .xsession
      - uses: actions/checkout@v1
      - name: shellcheck .pfetchrc
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .pfetchrc
      - uses: actions/checkout@v1
      - name: shellcheck .bin/openbsd/doas
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: .bin/openbsd/doas
