name: vint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Vint .vimrc
        uses: ludvighz/vint-action@v1
        with:
          args: --verbose --style-problem --color
          path: .vimrc
      - uses: actions/checkout@v1
      - name: Vint .exrc
        uses: ludvighz/vint-action@v1
        with:
          args: --verbose --style-problem --color
          path: .exrc
