---

# This file defines automation actions
name: Weekly

# Run automations weekly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

# Define a job for each automatic task
jobs:

  # This job updates all submodeules
  update submodules:
    runs-on: ubuntu-latest
    steps:

      # Checkout main code
      - uses: actions/checkout@v2

      # Set environment variables to allow configuration
      - name: Set env
        run: |
          echo "GITHUB_NEW_BRANCH=GIT_000_submodule_update" >> $GITHUB_ENV
